# Generated by Django 5.2.8 on 2025-12-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('oficios', models.CharField(help_text='Lista de oficios separados por comas', max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='trabajo_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha_acordada', models.DateField(help_text='Fecha acordada para la realización del trabajo.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArreglaTodo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='trabajo_realizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('realizado', models.BooleanField(default=False)),
                ('trabajo_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArreglaTodo.trabajo_pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArreglaTodo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('trabajo_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArreglaTodo.trabajo_realizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArreglaTodo.usuario')),
            ],
        ),
    ]
