# Generated by Django 5.2.8 on 2025-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArreglaTodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='oficios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='oficios',
            field=models.ManyToManyField(help_text='Selecciona los oficios que realiza este usuario.', to='ArreglaTodo.oficio'),
        ),
    ]
