# Generated by Django 5.2.8 on 2025-12-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArreglaTodo', '0002_oficio_remove_usuario_oficios_usuario_oficios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo_pedido',
            options={'verbose_name': 'Trabajo Pedido', 'verbose_name_plural': 'Trabajos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='trabajo_realizado',
            options={'verbose_name': 'Trabajo Realizado', 'verbose_name_plural': 'Trabajos Realizados'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
    ]
