# Generated by Django 5.2.8 on 2025-12-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArreglaTodo', '0003_alter_trabajo_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
    ]
