# Generated by Django 5.2.8 on 2025-12-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArreglaTodo', '0004_alter_oficio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['nombre'], 'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
    ]
